# fly.toml file generated for step-up-challenge-76be on 2022-08-27T17:48:02-04:00

app = "step-up-challenge-76be"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  exec = []

[[mounts]]
  destination = "/data"
  encrypted = false
  processes = []
  source = "data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "10s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
